on: push

jobs:
  push:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      #TODO Detect changes against current branch
      - name: Identify changes
        uses: dorny/paths-filter@v2
          id: identify-changes
          with:
            filters: |
              ui:
                - 'package.json'
                - 'package-lock.json'
                - 'ui/**'

      - name: Run UI tests
        if: steps.identify-changes.outputs.ui
        run: |
          npm ci
          sbt test

      - name: Publish UI
        if: ${{ steps.identify-changes.outputs.ui && (github.ref == 'refs/heads/master') }}
        run: ./.github/scripts/publish_ui.sh